version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/springbootaws-0.0.1-SNAPSHOT.war springbootaws-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - springbootaws-0.0.1-SNAPSHOT.war
     .ebextensions/**/*