version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/springbootaws.war springbootaws.war
artifacts:
  files:
    - springbootaws.war
     .ebextensions/**/*